// Code generated by errcodegen; DO NOT EDIT.

package errcodes

// ErrCode 错误码类型
//
// 全局错误码文档: https://developer.work.weixin.qq.com/document/path/90313
// 文档爬取时间: 2025-07-12 07:51:19 +0800
//
// NOTE: 关于错误码的名字为何如此无聊:
//
// 官方没有给出每个错误码对应的标识符，数量太多了
// 我也懒得帮他们想，反正有文档，就先这样吧
type ErrCode = int64
